package Ensamblador;

import java.awt.Desktop;
import java.io.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Harold Díaz
 */
public class Input extends javax.swing.JFrame {
    static String text;
    static int numOfLines = 0;
    
    public Input() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        jTextArea1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAyuda = new javax.swing.JButton();
        btnArchivo = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        labelCreditos = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ensamblador");
        setPreferredSize(new java.awt.Dimension(450, 337));
        getContentPane().setLayout(null);

        btnAyuda.setBackground(new java.awt.Color(0, 204, 204));
        btnAyuda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAyuda.setForeground(new java.awt.Color(255, 255, 255));
        btnAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/button_ayuda.png"))); // NOI18N
        btnAyuda.setBorder(null);
        btnAyuda.setBorderPainted(false);
        btnAyuda.setContentAreaFilled(false);
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAyuda);
        btnAyuda.setBounds(250, 260, 70, 30);

        btnArchivo.setBackground(new java.awt.Color(255, 255, 255));
        btnArchivo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnArchivo.setForeground(new java.awt.Color(255, 255, 255));
        btnArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/button_buscar-archivo.png"))); // NOI18N
        btnArchivo.setBorder(null);
        btnArchivo.setBorderPainted(false);
        btnArchivo.setContentAreaFilled(false);
        btnArchivo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(btnArchivo);
        btnArchivo.setBounds(260, 200, 160, 30);

        btnContinuar.setBackground(new java.awt.Color(0, 204, 204));
        btnContinuar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/button_continuar.png"))); // NOI18N
        btnContinuar.setBorder(null);
        btnContinuar.setBorderPainted(false);
        btnContinuar.setContentAreaFilled(false);
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(btnContinuar);
        btnContinuar.setBounds(340, 260, 90, 30);

        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("el área a la izquierda.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 150, 180, 30);

        labelCreditos.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        getContentPane().add(labelCreditos);
        labelCreditos.setBounds(360, 265, 90, 20);

        jLabel7.setForeground(new java.awt.Color(0, 255, 255));
        jLabel7.setText("archivo de texto o pegar en");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(250, 130, 180, 30);

        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("usuario. Puede copiar de un");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(250, 116, 180, 20);

        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setText("asegúrese de leer el manual de");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(250, 100, 180, 15);

        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Antes de ejecutar este programa,");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 80, 190, 20);

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ENSAMBLADOR");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 30, 180, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 230, 270);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 450, 337);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        try {
            File file = new File ("Manual de Usuario.txt");
            Desktop.getDesktop().open(file);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "El manual no se encuentra. Reinstale el programa.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAyudaActionPerformed
    
    private void btnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.txt", "txt");
        fileChooser.setFileFilter(filter);
        fileChooser.showOpenDialog(fileChooser);
        try {
            String path = fileChooser.getSelectedFile().getAbsolutePath();
            DataInputStream dis = new DataInputStream(new FileInputStream(path));
            BufferedReader bf = new BufferedReader(new InputStreamReader(dis));
            String line;
            while ((line = bf.readLine()) != null) {
                jTextArea1.append(line+" ");
                jTextArea1.append(System.getProperty("line.separator"));
                numOfLines++;
            }
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Archivo no encontrado. Intente otra vez. ", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException e) {
            
        } catch (IOException | IndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(null, "Error al leer archivo. Intente otra vez. ", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnArchivoActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        text = jTextArea1.getText();
        Info.read();
        Info.linesOfCodeSection = Info.section.indexOf(".data");
        if (Info.linesOfCodeSection < 0) {
            JOptionPane.showMessageDialog(null, "Sección .data no encontrada.", "Error", JOptionPane.ERROR_MESSAGE);
            Info.ok = false;
        }
        if (Info.ok) {
            Info.dataSymbols = new String[numOfLines - Info.linesOfCodeSection];
            Info.nums = new int [Info.linesOfCodeSection];
            Info.checkMnemos();
            for (int i=Info.linesOfCodeSection; i<numOfLines; i++) {
                Info.dataSymbols[i-Info.linesOfCodeSection] = Info.label.get(i);
            }
            Info.getOutput();
            Output a = new Output();
            a.setVisible(true);
        }
        this.setVisible(false);
        if(!Info.ok) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            /*for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }*/
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArchivo;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelCreditos;
    // End of variables declaration//GEN-END:variables
}
