package Ensamblador;

import java.awt.Desktop;
import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.UIManager;

/**
 *
 * @author Harold Díaz
 */
public class Output extends javax.swing.JFrame {

    public void writeToTextArea(String path, JTextArea jTextArea1) {
        try {
            DataInputStream dis = new DataInputStream(new FileInputStream(path));
            BufferedReader bf = new BufferedReader(new InputStreamReader(dis));
            String line;
            while ((line = bf.readLine()) != null) {
                jTextArea1.append(line);
                jTextArea1.append(System.getProperty("line.separator"));
            }
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Archivo no encontrado. Intente otra vez. ", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException e) {
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error al leer archivo. Intente otra vez. ", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public Output() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        writeToTextArea("output_cpp.txt", cppTextArea);
        writeToTextArea("output_vhdl.txt", vhdlTextArea);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAbrirArchivos = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        vhdlTextArea = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        cppTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ensamblador");
        setPreferredSize(new java.awt.Dimension(450, 337));
        getContentPane().setLayout(null);

        btnAbrirArchivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/button_abrir-archivos.png"))); // NOI18N
        btnAbrirArchivos.setBorderPainted(false);
        btnAbrirArchivos.setContentAreaFilled(false);
        btnAbrirArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirArchivosActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbrirArchivos);
        btnAbrirArchivos.setBounds(260, 260, 158, 30);

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/button_atras.png"))); // NOI18N
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras);
        btnAtras.setBounds(30, 260, 80, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VHDL");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 20, 50, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("C++");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 20, 40, 30);

        vhdlTextArea.setColumns(20);
        vhdlTextArea.setRows(5);
        jScrollPane2.setViewportView(vhdlTextArea);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(240, 50, 180, 190);

        cppTextArea.setColumns(20);
        cppTextArea.setRows(5);
        jScrollPane1.setViewportView(cppTextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 50, 180, 190);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 450, 337);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Input a = new Input();
        Info.section = new ArrayList<>();
        Info.label = new ArrayList<>();
        Info.mnemo = new ArrayList<>();
        Info.operands = new ArrayList<>();
        Info.ok = true;
        Input.numOfLines = 0;
        Input.text = "";
        Info.instrSymbols.clear();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnAbrirArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirArchivosActionPerformed
        try {
            File file = new File ("output_cpp.txt");
            Desktop.getDesktop().open(file);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Archivo no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
        }
        try {
            File file = new File ("output_vhdl.txt");
            Desktop.getDesktop().open(file);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Archivo no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAbrirArchivosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Output().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirArchivos;
    private javax.swing.JButton btnAtras;
    private javax.swing.JTextArea cppTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea vhdlTextArea;
    // End of variables declaration//GEN-END:variables
}
