/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desensamblador;

import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Harold Díaz
 */
public class Window extends javax.swing.JFrame {
    String output = "";
    String[] mnemo;
    
    public Window() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        outputArea.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        inputArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Desensamblador");
        setPreferredSize(new java.awt.Dimension(450, 337));
        setSize(new java.awt.Dimension(450, 337));
        getContentPane().setLayout(null);

        inputArea.setColumns(20);
        inputArea.setRows(5);
        jScrollPane3.setViewportView(inputArea);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 70, 170, 190);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("salida a la derecha. Se recomienda guardarla en un archivo .csv");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 50, 420, 20);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Coloque las instrucciones en hexadecimal a la izquierda, cada una");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 10, 420, 20);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("separada por un salto de línea. Presione continuar para obtener la");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 30, 420, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/button_continuar.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 260, 90, 40);

        outputArea.setColumns(20);
        outputArea.setRows(5);
        jScrollPane2.setViewportView(outputArea);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(200, 70, 230, 190);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 450, 337);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void read() {
        try {
            String text = inputArea.getText();
            String[] lines = text.split("\n");
            for (int i=0; i<lines.length; i++) {
                if (lines[i].endsWith(",")) {
                    lines[i] = lines[i].substring(0, lines[i].length()-1);
                }
                if (lines[i].endsWith("\"")) {
                    lines[i] = lines[i].substring(0, lines[i].length()-1);
                }
                lines[i] = lines[i].substring(2);
                output = output.concat(lines[i].toLowerCase()+";");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No hay texto o está en un formato inadecuado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void checkMnemos(int number, int index) {
        int quotient = number / 0x100;
        //int remainder = number % 0x100;
        switch (quotient) {
            case 0:
                mnemo[index] = "load"; break;
            case 1:
                mnemo[index] = "store"; break;
            case 2:
                mnemo[index] = "add"; break;
            case 3:
                mnemo[index] = "sub"; break;
            case 4:
                mnemo[index] = "input"; break;
            case 5:
                mnemo[index] = "output"; break;
            case 6:
                mnemo[index] = "jpos"; break;
            case 7:
                mnemo[index] = "jneg"; break;
            case 8:
                mnemo[index] = "jz"; break;
            case 9:
                mnemo[index] = "jnz"; break;
            case 10:
                mnemo[index] = "jmp"; break;
            case 11:
                mnemo[index] = "halt"; break;
            default:
                mnemo[index] = "N/A";
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        outputArea.setText("");
        read();
        String [] hex = output.split(";");
        final int NUM_INSTR = hex.length;
        int[] numbers = new int[NUM_INSTR];
        mnemo = new String[NUM_INSTR];
        outputArea.append("HLL;SECTION;LABEL;MNEMO;OPERANDS;COMMENTS;ADDR;CONT");
        outputArea.append(System.getProperty("line.separator"));
        for (int i=0; i<NUM_INSTR; i++) {
                numbers[i] = Integer.parseInt(hex[i], 16);
                checkMnemos(numbers[i], i);
                String section = (i==0)? ".code":"";
                String str = ";"+section+";;"+mnemo[i]+";"+";;"+String.format("0x%02X", i).substring(2)+";"+String.format("0x%03X", numbers[i]);
                outputArea.append(str);
                outputArea.append(System.getProperty("line.separator"));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (@SuppressWarnings("unused") javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al abrir el programa. ", "Error", JOptionPane.ERROR_MESSAGE);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea inputArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea outputArea;
    // End of variables declaration//GEN-END:variables
}
